#! /data/data/con.termux/files/usr/bin/bash
pkg install wget -y > /dev/null 2>&1
wget -q --spider https://google.com
case $? in
0)
cd $HOME
clear
echo -e '\e[33;1mLoading [         ]'
sleep 2.0
clear
apt-get update -y && apt-get upgrade -y
clear
echo -e '\e[33;1mLoading [==>      ]'
sleep 2.0
clear
apt-get install scrypt python python2 ruby php -y
clear
echo -e '\e[33;1mLoading [=====>   ]'
sleep 2.0
clear
gem install lolcat
clear
echo -e '\e[33;1mLoading [========>]'
sleep 2.0
clear
echo -e '\n\e[32;1mInstalation completed\e[0m'
;;
*)
sleep 2.0
echo -e "\e[31;1m\nYou are not connected to internet"
sleep 2.0
echo -e "\e[31;1mPlease connect to the internet"
sleep 2.0
echo -e "\e[32;1mExiting\n"
sleep 2.0
exit 4
;;
esac
